server:
  port: 9998

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
#        dialect: org.hibernate.dialect.OracleDialect

#  mybatis:
#    mapper-locations: classpath:mapper/*.xml

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testStudy;MODE=Oracle
    username: sa
    password:

#  defer-datasource-initialization: true

  messages:
    basename: message, config.i18n.messages

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  sql:
    init:
      mode: always